services:
  db:
    image: mysql:5.7
    container_name: db
    platform: linux/x86_64  # M1 Macの場合必要
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./backend/db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    command: --port 3306
    tty: true
    networks:
      - sns-network


  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - sns-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    networks:
      - sns-network

# data系、権限まわりがめんどくさいのでここにマウント
volumes:
  mysql_data:
    driver: local

networks:
  sns-network:
    driver: bridge 

